### ISSUE TITLE
Do we need to project mosaics before predicting birds?

### ISSUE THREAD

**Issue by bw4sz** [weecology/EvergladesTools#104]
The current snakemake workflow performs project_mosaics.py before predict_birds.py. For those colonies that have no georeferencing, this breaks the workflow and predictions are never made. There isn't any reason we can't run predictions on non-projected data, it just can't be used in bird-bird-bird or aggregated into the single .shp. I currently just added a raise value to more gracefully kill the job, but we need to decide if we want to make these predictions and stash them somewhere for other uses. For example, Lindsey often flies these colonies to get us rarer species.

**Comment by bw4sz** [comment]
I'm looking into dynamic DAGs in snakemake, 

https://stackoverflow.com/questions/69044425/snakemake-ignore-failed-path-and-redefine-inputs-for-a-common-rule

so that we can 'branches' in our snakefile. We want to run predict_birds on all files, but don't need them all to end up in nest_detection.

**Comment by ethanwhite** [comment]
All of the orthos should have georeferencing right? It just won't be as precise for the ones without ground control points. I've added #130 to address the orthos that are missing projections for some reason. If you agree please go ahead and close.

**Comment by ethanwhite** [comment]
Everything is work now for all orthos after cleaning up missing projections.
