### ISSUE TITLE
(Re)create Orthomosaics 

### ISSUE THREAD

**Issue by ethanwhite** [weecology/EvergladesTools#114]
The following flights either never had orthomosaics made or have what appears to be a serious issue with the orthomosaic that requires it to be rebuilt. More may be added as I finish fully understanding all the unsolved problems in #108.

@bw4sz & @henrykironde - can you please team up to get this taken care of by the end of next week (Jan 13) at the latest and use this process to finish developing a smoothly running, fully documented, workflow for creating orthomosaics as new data comes in this semester. Please upload the resulting files to the appropriate Dropbox folder and once that is done sync them to the HPG.

## No existing orthomosaics

- [x]  Jerrod, 5/24/22, orthos in Dropbox end on 5/9 but raw data exists for 5/24/22 that has not been orthorectified
- [x] Vacation, 6/9/22, orthos in Dropbox end on 6/1 but raw data exists for 6/9/22 that has not been orthorectified
- [x] Vacation, 05_19_2022A
- [x] Vacation, 05_26_2022A
- [x] Vacation, 05_26_2022B

## Orthomosaics that need to be rebuilt

- [x] JetportSouth, 2021-04-13, large number of missing areas presumably due to orthrectification, it's like the gov't redacted the colony!, **redo orthorectification**
- [x] JetportSouth, 2021-04-26, large number of missing areas presumably due to orthrectification,  **redo orthorectification**

**Comment by bw4sz** [comment]
Looking at this now. @henrykironde let me know when we can do this, but it'll have to be the new local machine, I don't have agisoft.

**Comment by henrykironde** [comment]
` JetportSouth, 2021-04-13` and `JetportSouth, 2021-04-26` are still showing holes, I have tried different values and I have one setup running, I think we shall have a better understanding after the current processes is complete(~5hr runtime).

**Comment by ethanwhite** [comment]
Thanks @henrykironde! 

Can you upload the completed ones to the appropriate Dropbox folder when you get the chance?

For the two JetportSouth flights - it's possible that there are inherent limitations on those flights, which is why the holes were there in the first place, so if you're reproducing other orthorectifications successfully and the holes are still there for those flights that's OK. Just let me know and we can close this issue.

**Comment by henrykironde** [comment]
Note: I have rebuilt the Orthomosaics using LZW vs JPEG

**Comment by henrykironde** [comment]
Regenerating these orthos to remove the alpha channel.

**Comment by ethanwhite** [comment]
All orthos regenerated that we're aware of needing
