### ISSUE TITLE
Image file problems to be fixed

### ISSUE THREAD

**Issue by ethanwhite** [weecology/EvergladesTools#38]
## Non-standard filenames

- [x] AlleyNorth_02132020-0-0.tif
- [x] AlleyNorth_02132020-0-1.tif
- [x] AlleyNorth_02132020-0-2.tif
- [x] AlleyNorth_02132020-0-3.tif
- [x] AlleyNorth_02132020-0-4.tif
- [x] AlleyNorth_02132020-0-5.tif
- [x] AlleyNorth_02132020-0-6.tif
- [x] AlleyNorth_02132020-0-7.tif
- [x] AlleyNorth_02132020-0-8.tif

## Incorrect number of channels

- [x] JetportSouth_04_07_2020.tif
- [x] Vacation_05_19_2020.tif

## Projection problems

- [x] Jerrod_03_03_2021.tif
- [x] Joule_05_05_2021.tif
- [x] Hidden_03_22_2021.tif

## Not sure (tossed in `predict.py` but can't remember why)

- [x]  AlleyNorth_02_23_2021.tif

**Comment by ethanwhite** [comment]
Current errors at transformation step:

* Joule_05_05_2021_BottomHalf_Identified Nests.tif
* Joule_05_05_2021_TopHalf_Identified Nests.tif
* Jerrod_05_05_2021_Identified Nests.tif
* Jerrod_03_03_2021.tif
* Joule_05_05_2021.tif

**Comment by ethanwhite** [comment]
No predictions being made for:

* Forseti_02_11_2021
* Jerrod_03_31_2021
* Hidden_03_22_2021

"The size of tensor a (4) must match the size of tensor b (3) at non-singleton dimension 0":

* Vacation_05_19_2020
* JetportSouth_04_07_2020

**Comment by ethanwhite** [comment]
All of the orthos reference in two comments have been moved to `/blue/ewhite/everglades/problem_orthos` for further exploration.

**Comment by ethanwhite** [comment]
The current copy of `Joule_05_05_2021.tif` in Dropbox and on HPG is a partial raster that appears to have been download scale that has been used for identifying field nests. I suspect it's the same files as `Joule_05_05_2021_BottomHalf_Identified Nests.tif` and maybe represents an accidental oversave. I suspect that the full data underlying this file is in `Joule_05_05_2021_-0-0.tif` and `Joule_05_05_2021_-0-1.tif`, which are in Dropbox but not on the HPG.

**Comment by ethanwhite** [comment]
Fixes:

* Merged `Joule_05_05_2021_-0-0.tif` and `Joule_05_05_2021_-0-1.tif` as a replacement for `Joule_05_05_2021.tif`
* Stripped alpha channel from `JetportSouth_04_07_2020.tif` and `Vacation_05_19_2020.tif` using https://support.skycatch.com/hc/en-us/articles/219178537-Removing-the-Alpha-Channel-from-Your-Orthotiff

**Comment by ethanwhite** [comment]
I uploaded the fixed `Joule_05_05_2021` to Dropbox. I don't have access to the 2020 folder already so the changes to `JetportSouth_04_07_2020.tif` and `Vacation_05_19_2020.tif` are only on the HPG in `/blue/ewhite/everglades/orthomosaics`

**Comment by bw4sz** [comment]
I also am collecting problem info 

* /blue/ewhite/everglades/orthomosaics/2022/6thBridge/6thBridge_02_10_2022_SV_Counted.tif I believe should be deleting once Lindsey confirms it was misnamed.

**Comment by ethanwhite** [comment]
We have successfully completed a from scratch from of the workflow, which means that these problems are generally solved (thanks to hours and hours of work; thanks @henrykironde @skmorgane @bw4sz !!). Any new issues that come up should be added as new issues.
