### ISSUE TITLE
Implement negative mining to reduce lily pad detections by bird detector

### ISSUE THREAD

**Issue by ethanwhite** [weecology/EvergladesTools#42]
There are currently a large number of lily pads at the edge of colonies being detected as birds (and therefore also nests). This is worse in 2021 presumably due to differences in hydrology. We need to update the Everglades bird detector model with negative mining using empty frames. Hopefully that will be sufficient, but if not we may need to label some regions with both birds and lily pads

**Comment by bw4sz** [comment]
Can this be closed?

**Comment by ethanwhite** [comment]
We made some modest progress, but it wasn't really sufficient. We can keep playing around with the empty frames or we could try adding an explicit lily pad class.

**Comment by ethanwhite** [comment]
Done
